_BASE_: ../maskformer2_mmseg.yaml
MODEL:
  BACKBONE:
    NAME: "BEiTAdapterLargeBackbone"
  WEIGHTS: "beitv2_large_patch16_224_pt1k_ft1k_stage1.pkl"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
